import io
import os
from datetime import datetime

import markdown2
from xhtml2pdf import pisa


_CSS = """
body { font-family: Helvetica, Arial, sans-serif; font-size: 11px; color: #222; margin: 40px; }
h1 { color: #1a1a2e; border-bottom: 2px solid #1a1a2e; padding-bottom: 8px; font-size: 20px; }
h2 { color: #16213e; margin-top: 20px; font-size: 16px; }
h3 { color: #0f3460; font-size: 13px; }
table { border-collapse: collapse; width: 100%; margin: 10px 0; }
th, td { border: 1px solid #ccc; padding: 6px 10px; text-align: left; font-size: 10px; }
th { background-color: #1a1a2e; color: white; }
tr:nth-child(even) { background-color: #f5f5f5; }
code { background-color: #f0f0f0; padding: 2px 4px; font-size: 10px; }
pre { background-color: #f0f0f0; padding: 10px; font-size: 10px; overflow-x: auto; }
.header { text-align: center; margin-bottom: 20px; }
.header h1 { font-size: 22px; margin-bottom: 4px; }
.header p { color: #666; font-size: 11px; margin: 2px 0; }
.footer { text-align: center; font-size: 9px; color: #999; margin-top: 30px; border-top: 1px solid #ccc; padding-top: 8px; }
"""

_HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>{css}</style></head>
<body>
<div class="header">
    <h1>Stock Analysis Report</h1>
    <p><strong>{exchange}:{ticker}</strong> | Profile: {profile} | {date}</p>
</div>
{content}
<div class="footer">
    Generated by AG-UC-0999 Stock Analysis Agent | This report is for informational purposes only and does not constitute financial advice.
</div>
</body>
</html>"""


def markdown_to_pdf(report_md: str, ticker: str, exchange: str, profile: str) -> bytes:
    """Convert a markdown report to styled PDF bytes."""
    html_content = markdown2.markdown(
        report_md,
        extras=["tables", "fenced-code-blocks", "header-ids", "strike", "task_list"],
    )
    full_html = _HTML_TEMPLATE.format(
        css=_CSS,
        exchange=exchange.upper(),
        ticker=ticker.upper(),
        profile=profile,
        date=datetime.now().strftime("%Y-%m-%d %H:%M"),
        content=html_content,
    )
    buffer = io.BytesIO()
    pisa.CreatePDF(io.StringIO(full_html), dest=buffer)
    return buffer.getvalue()


def save_pdf_to_disk(pdf_bytes: bytes, ticker: str, exchange: str, reports_dir: str = "reports") -> str:
    """Save PDF bytes to the reports directory. Returns the file path."""
    os.makedirs(reports_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
    filename = f"{exchange.upper()}_{ticker.upper()}_{timestamp}.pdf"
    filepath = os.path.join(reports_dir, filename)
    with open(filepath, "wb") as f:
        f.write(pdf_bytes)
    return filepath
